### ISSUE TITLE
Custom exposure/acquisition time

### ISSUE THREAD

**Issue by mrakitin** [BNL-ATF/ophyd-basler#7]
We need to be able to configure a custom exposure/acquisition time for the Basler cameras via `pypylon`.

**Comment by mrakitin** [comment]
This example can be useful: https://github.com/scivision/basler-pypylon-examples/blob/4c4dd3fbb15986d7ca2808873ea190a194e35e06/SingleImage.py#L19.

@thomaswmorris, will you have time to look at the task?

**Comment by thomaswmorris** [comment]
I can tackle this, sure!
